### ISSUE TITLE
Failure Insufficient Fee thrown -> asset creation

### ISSUE THREAD

**Issue by jluetzow** [NemProject/nem-library-ts#1]
Announcing a signed `AssetDefinitionCreationTransaction` is throwing `FAILURE_INSUFFICIENT_FEE`

**Comment by voycey** [comment]
The fee calculation needs to happen by fetching the currentSupply not the initialSupply as discussed here:

https://github.com/QuantumMechanics/NEM-sdk/issues/36#issuecomment-409997739

Especially for mutable Mosaics
